name: Build Image and Publish to GCR

on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: true
      checked-out-sha:
        type: string
        required: true
    outputs:
        dockerImageTag: 
          description: "The image written to the GCR"
          value: ${{ jobs.build-image.outputs.dockerImageTag }}

concurrency:
     group: ${{ github.workflow }}-${{ github.event.inputs.environment }}
     cancel-in-progress: true

env:
    DOCKER_IMAGE: early-years-qualification
    GITHUB_CONTAINER_REGISTRY: ghcr.io
    ORG_NAME: dfe-digital
    CHECKED_OUT_SHA: ${{ inputs.checked-out-sha }}

jobs:

    build-image:

        runs-on: ubuntu-22.04
        name: Build & Publish Image
        outputs:
          dockerImageTag: ${{ steps.image.outputs.dockerImageTag }}
        steps:

            - name: Checkout Repository
              uses: actions/checkout@v6
              with:
                ref: ${{ github.ref }}

            - name: GitHub Container Registry Login
              uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
              with:
                registry: ${{ env.GITHUB_CONTAINER_REGISTRY }}
                username: ${{ github.repository_owner }}
                password: ${{ secrets.GITHUB_TOKEN }}
                
            - name: Format branch name
              env:
                BRANCH_NAME: ${{ inputs.branch }}
              run: |
                branchName="${BRANCH_NAME}"
                echo FORMATTED_BRANCH_NAME="${branchName//\//-}" >> $GITHUB_ENV

            - name: Build Image & Publish To GCR
              uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7.1.0
              with:
                context: ./
                file: ./src/Dfe.EarlyYearsQualification.Web/Dockerfile
                build-args: COMMIT_SHA=${{ env.CHECKED_OUT_SHA }}
                tags: |
                    ${{ env.GITHUB_CONTAINER_REGISTRY }}/${{ env.ORG_NAME }}/${{ env.DOCKER_IMAGE }}:${{ env.FORMATTED_BRANCH_NAME }}-${{ env.CHECKED_OUT_SHA }}
                push: true

            - name: Output Docker Image Tag
              id: image
              run: echo "dockerImageTag=${{ env.GITHUB_CONTAINER_REGISTRY }}/${{ env.ORG_NAME }}/${{ env.DOCKER_IMAGE }}:${{ env.FORMATTED_BRANCH_NAME }}-${CHECKED_OUT_SHA}" >> $GITHUB_OUTPUT